---

- hosts: all
  become: true
  tasks:
         
  - name: installing apache2 and php  packages
    apt: 
      name: 
        - "{{ apache_package}}"
        - "{{ php_package }}"
      state: latest
      update_cache: true
    when: ansible_distribution == 'ubuntu'
