---

- hosts: all
  become: true
  tasks:
         
  - name: installing apache2 and php  packages
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: true
    when: ansible_distribution == 'ubuntu'
