---

- hosts: all
  become: true
  tasks:

         
  - name: deleting apache2 package
    apt: 
      name: apache2
      state: absent
 
  - name: deleting php support for apache
    apt: 
      name: libapache2-mod-php
      state: absent

