- hosts: all
  become: true
  pre_tasks:
  - name: install updates(Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'







