- hosts: all
  become: true
  pre_tasks:

  - name: install updates(Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages
    tags: ubuntu, apache, apache2
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: copying default html file to apache2
    tags: html,apache
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644



- hosts: db_servers
  tags: ubuntu,db,mariadb
  become: true
  tasks: 

  - name: install mariadb package(Ubuntu)
    apt: 
      name: mariadb
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install mariabd package (Centos)
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == 'Centos'


- hosts: file_servers
  become: true
  tasks: 
  
  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest


